### ISSUE TITLE
Cannot install the module due to a failed font test.

### ISSUE THREAD

**Issue by ramillies** [timo/cairo-p6#11]
The test called "text extents height" fails on my system, which currently prevents me from installing the module. 

    ╰─[:--)]--➤  zef install Cairo
    ===> Searching for: Cairo
    ===> Testing: Cairo:ver('0.2.2')
    
    # Failed test 'text extents height'
    # at t/text.t line 24
    #     expected approximately: 7
    #                        got: 8
    # maximum relative tolerance: 1e-06
    # actual relative difference: 0.125
    # Looks like you failed 1 test of 9
    
    ===> Testing [FAIL]: Cairo:ver('0.2.2')
    Aborting due to test failure: Cairo:ver('0.2.2') (use --force-test to override)
    (... blah blah blah, complete call stack follows ...)

Why I believe this happens: The test in question does `.select-font-face("courier", ...)`. I have no idea where that font face goes, but there is no font called exactly "courier" on my system (`fc-list | grep courier` fails), so perhaps the text is rendered with totally different font. Maybe the test should use a font which is as omnipresent as possible (but, sadly, I don't have any idea about what would that be...)

(I don't think it's anything serious. I guess I just can use `--force-test` and that's it. But it's always nice when a module installs without interventions like this :—))

**Edit**: I forced installing the module and produced the same image as in the test. My hypothesis above is probably wrong since the font in the image truly *is* Courier...

**Comment by dwarring** [comment]
Quiet right. Cairo make no guarantees as to which particular font will be selected or substituted on a given platform.

I'm made that test far more approximate and forgiving. Hope that works on all systems.
