### ISSUE TITLE
Bessel curve ？

### ISSUE THREAD

**Issue by ccworld1000** [timo/cairo-p6#18]
Does it have Bessel curve function? It seems that no correlation has been found.

**Comment by ccworld1000** [comment]
![lines](https://raw.githubusercontent.com/ccworld1000/CCChart/master//doc/screenshot/default_lines.png)



It may also want to have Bessel curve chart.

**Comment by Xliff** [comment]
Actually, cairo_path_t is what would implement the Bessel Curve in Cairo. I am currently working on adding this.

**Comment by Xliff** [comment]
My latest PR now has the code needed to generate curves using Cairo.
