### ISSUE TITLE
There seem to be some errors in Travis

### ISSUE THREAD

**Issue by JJ** [timo/cairo-p6#23]
https://travis-ci.com/JJ/cairo-p6/builds/100354309?utm_medium=notification&utm_source=email

**Comment by schmidh** [comment]
Just for info: same on Ubuntu 18.04. (bionic). Travis build is on Ubuntu 14.04 (trusty).

**Comment by dwarring** [comment]
Working for me on Rakudo 2018.12 and 2019.03.

Travis has until now just been testing against the bleed.  Have setup a second travis job to regression test against 2018.12 486a463   https://travis-ci.org/timo/cairo-p6/jobs/508726655

**Comment by dwarring** [comment]
Seems like this was temporary issue with the Rakudo blead.
