### ISSUE TITLE
Enums in Cairo are not being found, even though they are 'is export'

### ISSUE THREAD

**Issue by Xliff** [timo/cairo-p6#24]
Here is the test case:

```
cbwood@Infinity4:~/Projects/p6-GooCanvas$ perl6 -e 'use Cairo; say FillRule.enums'
===SORRY!=== Error while compiling -e
Undeclared name:
    FillRule used at line 1
```

Which is odd, because it is marked as "is export", [here](https://github.com/timo/cairo-p6/blob/master/lib/Cairo.pm6#L999)

Is this an error with Perl6 or with the Cairo module?

**Comment by dwarring** [comment]
Working for me:
```
 perl6 -v
This is Rakudo version 2019.03.1-235-g235f14cd5 built on MoarVM version 2019.03-97-g8fef19994
implementing Perl 6.d.
% perl6 -e'use Cairo; say FillRule.enums'
Map.new((FILL_RULE_EVEN_ODD => 1, FILL_RULE_WINDING => 0))
```
Maybe your installed Cairo isn't up-to-date?

**Comment by Xliff** [comment]
Was not working for someone else in IRC. I went through and reinstalled after a recompile of rakudo (moar-blead -> moar-master) and it went away.

I will close this. If problem re-occurs, I will re-open.

**Comment by dwarring** [comment]
I've bumped the version number, which should help. Part of the problem was not being able to easily upgrade from an earlier Cairo 0.2.4 to get the newer Enums.
