### ISSUE TITLE
CI fails on alpine linux

### ISSUE THREAD

**Issue by melezhik** [timo/cairo-p6#30]
Hi!

http://sparrowhub.io:2222/report/200

HTH

PS this is tested on alpine linux

**Comment by dwarring** [comment]
@melezhik I've adjusted the failing test

**Comment by melezhik** [comment]
sure. if you want to test it - please consider this PR - https://github.com/timo/cairo-p6/pull/31
then @timo needs to set up this repo in SparkyCI to trigger builds ...

**Comment by melezhik** [comment]
Anyway,  I've fetched this commit to may fork branch and let's wait for a new SparkyCI build a bit ...

**Comment by melezhik** [comment]
Fixed now in CI - sparrowhub.io:2222/report/204

**Comment by dwarring** [comment]
Thanks
